<div style="
    display: flex; 
    align-items: center; 
    gap: 35px; 
    padding: 20px; 
    border-radius: 15px; 
    background: linear-gradient(90deg, #1e293b, #334155); 
    box-shadow: 0 4px 15px rgba(0,0,0,0.3);
">
  <img src="https://i.postimg.cc/63z6zg41/EMGE.jpg" width="130" style="
    border-radius: 50%;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    box-shadow: 0 5px 15px rgba(0,0,0,0.4);
  " 
  onmouseover="this.style.transform='scale(1.2)'; this.style.boxShadow='0 8px 25px rgba(0,0,0,0.5)';"
  onmouseout="this.style.transform='scale(1)'; this.style.boxShadow='0 5px 15px rgba(0,0,0,0.4)';">
  <div>
    <h1 style="margin-bottom: 5px; font-family: 'Roboto', sans-serif; color: #f8fafc;">📊 Course 02: NumPy basics</h1>
    <p style="font-size: 16px; margin-top: 0; color: #e2e8f0;">
      Build your NumPy skills from the ground up.
    </p>
    <p style="font-size:14px; color:#cbd5e1; margin-top: 5px;">
      Version 0.0 | Data & AI Club EMGE
    </p>
    <hr style="border: none; border-top: 1px solid #475569;">
    <p style="font-size: 14px; color: #94a3b8;">
      🧠 <b>Data & AI Club EMGE</b><br>
      © 2025 All Rights Reserved
    </p>
  </div>
</div>



<div style="
  width: 100%;
  padding: 40px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 8px 25px rgba(0,0,0,0.4);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
  box-sizing: border-box;
">
  <h1 style="margin-top: 0; font-size: 32px; color: #38bdf8;">📊 Welcome to NumPy Foundations</h1>
  <p style="font-size: 18px; line-height: 1.8; color: #e2e8f0;">
    This course is your gateway to mastering <strong>NumPy</strong>, the core library for numerical computing in Python. Whether you're analyzing data, building models, or preparing for machine learning, NumPy gives you the tools to work efficiently with arrays and matrices.
  </p>
  <p style="font-size: 17px; color: #cbd5e1;">
    You'll start with the basics—creating arrays, performing operations, and reshaping data—and gradually build toward real-world applications in data science and AI.
  </p>

  <div style="margin-top: 30px;">
    <h2 style="font-size: 24px; color: #60a5fa;">🗂️ Course Plan</h2>
    <ul style="font-size: 16px; color: #e2e8f0; line-height: 1.8; padding-left: 20px;">
      <li><strong>Module 0:</strong> Introduction to NumPy</li>
      <li><strong>Module 1:</strong> Creating and Inspecting Arrays</li>
      <li><strong>Module 2:</strong> Array Operations and Broadcasting</li>
      <li><strong>Module 3:</strong> Reshaping and Manipulating Arrays</li>
      <li><strong>Module 4:</strong> Other Ways of Creating an Array & Random Number Generation</li>
    </ul>
  </div>

  <hr style="border: none; border-top: 1px solid #475569; margin: 30px 0;">
  <p style="font-size: 15px; color: #94a3b8;">
    🧠 <strong>Data & AI Club EMGE</strong><br>
    Version 0.0 | © 2025 All Rights Reserved
  </p>
</div>


<div style="
  width: 100%;
  padding: 40px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 8px 25px rgba(0,0,0,0.4);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
  box-sizing: border-box;
">
  <h2 style="margin-top: 0; font-size: 28px; color: #38bdf8;">🔧 Understanding <code>np.array()</code></h2>
  <p style="font-size: 17px; line-height: 1.8; color: #e2e8f0;">
    The <code>np.array()</code> function is the core building block of NumPy. It creates a powerful, multidimensional array object from a regular Python list or tuple.
  </p>
  <p style="font-size: 16px; color: #cbd5e1;">
    Unlike Python lists, NumPy arrays support vectorized operations, are more memory-efficient, and enable fast mathematical computations.
  </p>
  <pre style="
    background-color: #0f172a;
    color: #f8fafc;
    padding: 15px;
    border-radius: 10px;
    font-size: 15px;
    overflow-x: auto;
  "><code>import numpy as np

data = [1, 2, 3, 4]
arr = np.array(data)

print(arr)  # Output: [1 2 3 4]</code></pre>
  <p style="font-size: 15px; color: #94a3b8;">
    🧠 Use <code>np.array()</code> to convert lists into efficient numerical arrays for computation.
  </p>
</div>


In [1]:
import numpy as np

In [2]:
vect1 = np.array([1, 2, 3])
vect2 = np.array([[1],
                 [2],
                 [3]])

In [3]:
print("vect1 shape:", vect1.shape)
print("vect2 shape:", vect2.shape)

vect1 shape: (3,)
vect2 shape: (3, 1)


In [4]:
vect1

array([1, 2, 3])

In [5]:
vect1.dtype

dtype('int64')

In [6]:
vect2

array([[1],
       [2],
       [3]])

In [7]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [8]:
matrix1.shape

(3, 3)

In [9]:
matrix1[2,1]

8

In [10]:
matrix1[:,1]

array([2, 5, 8])

In [11]:
matrix1[1:-1,1:-1]

array([[5]])

In [12]:
matrix3 = np.array([[1, 1, 1, 1, 1],
                    [1, 1, 1, 1, 1],
                    [1, 1, 1, 1, 1],
                    [1, 1, 1, 1, 1],
                    [1, 1, 1, 1, 1]])

In [13]:
matrix3.shape

(5, 5)

In [14]:
matrix3[1:-1,1:-1] = 0

In [15]:
matrix3

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [16]:
# multidimensional array
my_array = np.array([[[1, 2], 
                      [3, 4]],
                     [[5, 6], 
                      [7, 8]]])


In [17]:
my_array.shape

(2, 2, 2)

<div style="
  width: 100%;
  padding: 40px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 8px 25px rgba(0,0,0,0.4);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
  box-sizing: border-box;
">
  <h2 style="margin-top: 0; font-size: 28px; color: #38bdf8;">⚙️ Array Operations & Comparaison</h2>
  <p style="font-size: 17px; line-height: 1.8; color: #e2e8f0;">
    NumPy allows you to perform fast, element-wise operations on arrays—such as addition, subtraction, multiplication, and division—without writing explicit loops. These operations are optimized for performance and readability.
  </p>
  <pre style="
    background-color: #0f172a;
    color: #f8fafc;
    padding: 15px;
    border-radius: 10px;
    font-size: 15px;
    overflow-x: auto;
  "><code>import numpy as np

a = np.array([1, 2, 3])
b = np.array([10])

result = a + b  # Element-wise addition

print(result)  # Output: [11 12 13]</code></pre>
  <p style="font-size: 15px; color: #94a3b8;">
    ✴️ NumPy operations are concise, readable, and highly optimized for numerical tasks.
  </p>

  


In [18]:
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
matrix2 = np.array([[11, 12, 13], 
                    [14, 15, 16], 
                    [17, 18, 19]])

In [19]:
matrix1 + matrix2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [20]:
matrix2 - matrix1

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [21]:
matrix1 / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [22]:
matrix2 // 2

array([[5, 6, 6],
       [7, 7, 8],
       [8, 9, 9]])

In [23]:
matrix1 % 2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

<p style="font-size: 16px; color: #e2e8f0;">
  ✴️ The <code>*</code> operator in NumPy performs element-wise multiplication between arrays of compatible shapes.
</p>


In [24]:
matrix1 * matrix2 # element-wise mutliplication

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

<p style="font-size: 16px; color: #e2e8f0;">
  🔗 The <code>np.dot()</code> function performs matrix multiplication for 2D arrays and inner product for 1D vectors.
</p>


In [25]:
vect1 = np.array([1, 1, 1])
vect2 = np.array([[2],
                 [2],
                 [2]])

In [26]:
np.dot(vect1, vect2)

array([6])

In [27]:
np.dot(matrix1, matrix2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [28]:
np.dot(matrix1, vect2)

array([[12],
       [30],
       [48]])

<p style="font-size: 16px; color: #e2e8f0;">
  🔢 The <code>@</code> operator performs matrix multiplication and is equivalent to <code>np.matmul()</code> for 2D arrays.
</p>
<p style="font-size: 16px; color: #e2e8f0;">
  🧮 The <code>np.matmul()</code> function handles matrix multiplication across 1D, 2D, and higher-dimensional arrays with broadcasting support.
</p>


In [29]:
matrix1 @ matrix2

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [30]:
np.matmul(matrix1, matrix2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

<h2 style="font-size: 28px; color: #38bdf8; margin-top: 50px;">🔍 Array Comparison</h2>
  <p style="font-size: 16px; line-height: 1.8; color: #e2e8f0;">
    NumPy supports element-wise comparison using operators like <code>==</code>, <code>!=</code>, <code>&gt;</code>, <code>&lt;</code>, and functions like <code>np.array_equal()</code> to check if arrays are identical in shape and content.
  </p>
  <p style="font-size: 15px; color: #94a3b8;">
    🧠 These comparisons return boolean arrays or single values, making them useful for filtering, validation, and condition-based logic.
  </p>
</div>

In [31]:
matrix01 = np.array([[1, 2, 3],
                     [4, 5, 6]])
matrix02 = np.array([[10, 20, 30],
                     [40, 50, 60]])

In [32]:
matrix01 == matrix02

array([[False, False, False],
       [False, False, False]])

In [33]:
matrix02 / 10 == matrix01

array([[ True,  True,  True],
       [ True,  True,  True]])

In [34]:
matrix01 <= matrix02

array([[ True,  True,  True],
       [ True,  True,  True]])

In [35]:
matrix02 < matrix01

array([[False, False, False],
       [False, False, False]])

<div style="
  width: 100%;
  padding: 40px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 8px 25px rgba(0,0,0,0.4);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
  box-sizing: border-box;
">
  <h2 style="margin-top: 0; font-size: 28px; color: #38bdf8;">📐 Broadcasting in NumPy</h2>
  <p style="font-size: 16px; line-height: 1.8; color: #e2e8f0;">
    <strong>Broadcasting</strong> is a powerful feature that lets NumPy apply operations between arrays of different shapes. It automatically expands smaller arrays to match the shape of larger ones, enabling seamless computation.
  </p>
  <div style="margin: 20px 0; padding: 15px; background-color: #0f172a; border-radius: 10px;">
    <p style="font-size: 16px; color: #f8fafc; margin: 0;">
      📏 <strong>Broadcasting Rule:</strong><br>
      When operating on two arrays, NumPy compares their shapes element-wise starting from the trailing dimensions. Two dimensions are compatible when:
      <ul style="margin-top: 10px; padding-left: 20px; color: #f8fafc;">
        <li>They are equal, or</li>
        <li>One of them is 1</li>
      </ul>
      If the shapes are not compatible, NumPy raises a <code>ValueError</code>.
    </p>
  </div>
  <p style="font-size: 15px; color: #94a3b8;">
    🧠 Broadcasting simplifies code and boosts performance—no need for manual reshaping or looping.
  </p>
</div>


In [36]:
array1 = np.array([[1, 1, 1],
                   [1, 1, 1],
                   [1, 1, 1]]) # dimension (3, 3)
array2 = np.array([[2, 2, 2],
                   [2, 2, 2],
                   [2, 2, 2]]) # dimension (3, 3)
array3 = np.array([1]) # dimension (1, ) = (1, 1)
array4 = np.array([1, 2, 3, 4]) # dimension (4, ) = (1, 4)
array5 = np.array([[1],
                   [2],
                   [3],
                   [4]]) # dimension (4, 1)
array6 = np.array([1, 2, 3]) # dimension (3, ) = (1, 3)

In [37]:
array1 + array2  # element-wise addition    

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [38]:
array1 + array3

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [39]:
array4 + array5

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [40]:
array1 + array6

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

<div style="
  width: 100%;
  padding: 40px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 8px 25px rgba(0,0,0,0.4);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
  box-sizing: border-box;
">
  <h2 style="margin-top: 0; font-size: 28px; color: #38bdf8;">🧩 Reshape & Concatenate</h2>

  <p style="font-size: 17px; line-height: 1.8; color: #e2e8f0;">
    <code>reshape()</code> changes the structure of an array without altering its data. You must ensure that the total number of elements remains the same.
  </p>
  <pre style="
    background-color: #0f172a;
    color: #f8fafc;
    padding: 15px;
    border-radius: 10px;
    font-size: 15px;
    overflow-x: auto;
  "><code>import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
reshaped = a.reshape((2, 3))</code></pre>

  <p style="font-size: 16px; color: #cbd5e1;">
    <code>concatenate()</code> merges arrays along a specified axis. To use it, arrays must have the same shape in all dimensions except the one you're joining on.
  </p>
  <pre style="
    background-color: #0f172a;
    color: #f8fafc;
    padding: 15px;
    border-radius: 10px;
    font-size: 15px;
    overflow-x: auto;
  "><code>a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

Both arrays have shape (2, 2) → compatible for axis=0
merged = np.concatenate([a, b], axis=0)
Output shape: (4, 2)</code></pre>

  <p style="font-size: 15px; color: #94a3b8;">
    🧠 Use <code>reshape</code> to reorganize, <code>shape</code> to inspect, and <code>concatenate</code> to merge — but always check shape compatibility first.
  </p>
</div>


In [41]:
matrix00 = np.array([[1, 2, 3, 4, 5, 6],
                    [2, 3, 4, 5, 6, 7],
                    [3, 4, 5, 6, 7, 8],
                    [4, 5, 6, 7, 8, 9]])
matrix00.shape

(4, 6)

In [42]:
matrix00.reshape(2, 12)

array([[1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7],
       [3, 4, 5, 6, 7, 8, 4, 5, 6, 7, 8, 9]])

In [43]:
matrix00.reshape(8, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7],
       [3, 4, 5],
       [6, 7, 8],
       [4, 5, 6],
       [7, 8, 9]])

<h2>Understanding <code>axis</code> in NumPy</h2>

<p>The <code>axis</code> parameter tells NumPy <strong>which dimension</strong> to operate on. Think of it like choosing whether to go <em>down rows</em> (<code>axis=0</code>) or <em>across columns</em> (<code>axis=1</code>).</p>

<h3>Axis Reference Table</h3>
<table>
  <thead>
    <tr>
      <th>Axis Value</th>
      <th>Meaning</th>
      <th>Operation Direction</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>axis=0</code></td>
      <td>Operate <strong>down rows</strong></td>
      <td>Vertical (column-wise)</td>
    </tr>
    <tr>
      <td><code>axis=1</code></td>
      <td>Operate <strong>across columns</strong></td>
      <td>Horizontal (row-wise)</td>
    </tr>
    <tr>
      <td><code>axis=None</code></td>
      <td>Flatten array before operation</td>
      <td>No direction — 1D only</td>
    </tr>
  </tbody>
</table>

<h3>Visual Example: 2D Array</h3>
<pre><code>a = np.array([[1, 2, 3],
              [4, 5, 6]])
</code></pre>

<ul>
  <li><strong><code>np.sum(a, axis=0)</code></strong> → <code>[5, 7, 9]</code> <em>(sums each column)</em></li>
  <li><strong><code>np.sum(a, axis=1)</code></strong> → <code>[6, 15]</code> <em>(sums each row)</em></li>
  <li><strong><code>np.sum(a, axis=None)</code></strong> → <code>21</code> <em>(sum of all elements)</em></li>
</ul>

<h3>Axis in <code>np.concatenate</code></h3>
<pre><code>a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
</code></pre>

<ul>
  <li><strong><code>np.concatenate((a, b), axis=0)</code></strong> → <code>[[1, 2], [3, 4], [5, 6]]</code></li>
  <li><strong><code>np.concatenate((a, b.T), axis=1)</code></strong> → <code>[[1, 2, 5], [3, 4, 6]]</code></li>
  <li><strong><code>np.concatenate((a, b), axis=None)</code></strong> → <code>[1, 2, 3, 4, 5, 6]</code></li>
</ul>

<h3>When You Don’t Use <code>axis</code></h3>
<ul>
  <li>If omitted, NumPy uses the default:
    <ul>
      <li><code>np.concatenate</code> → <code>axis=0</code></li>
      <li><code>np.sum</code> → <code>axis=None</code></li>
    </ul>
  </li>
  <li>If you don’t care about direction, use <code>axis=None</code> to treat everything as 1D.</li>
</ul>


In [44]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], 
              [7, 8]])
np.concatenate((a, b), axis=1)


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [46]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [47]:
a = np.array([[[1, 2]], [[3, 4]]])  # shape (2, 1, 2)
b = np.array([[[5, 6]]])           # shape (1, 1, 2)
np.concatenate((a, b), axis=0)
# → shape (3, 1, 2)


array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [48]:
a = np.array([[[1], [2]], [[3], [4]]])  # shape (2, 2, 1)
b = np.array([[[5], [6]], [[7], [8]]])  # shape (2, 2, 1)
np.concatenate((a, b), axis=2)
# → shape (2, 2, 2)


array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [49]:
a = np.array([[1, 2]])
b = np.array([[3, 4, 5]])
np.concatenate((a, b), axis=0) #→ ❌ ValueError: shapes mismatch


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
a = np.array([])
b = np.array([1, 2])
np.concatenate((a, b))
# → [1. 2.]


In [ ]:
a = np.array([1, 2], dtype=np.int32)
b = np.array([3.5, 4.5], dtype=np.float64)
np.concatenate((a, b), casting='unsafe')
# → [1. 2. 3.5 4.5]


In [ ]:
row1 = np.array([[255, 0, 0], [0, 255, 0]])
row2 = np.array([[0, 0, 255], [255, 255, 0]])
np.concatenate((row1, row2), axis=0)
# → stacks image rows


In [ ]:
features1 = np.array([0.1, 0.2, 0.3])
features2 = np.array([0.4, 0.5])
np.concatenate((features1, features2))
# → [0.1 0.2 0.3 0.4 0.5]


<div style="
  width: 100%;
  padding: 40px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 8px 25px rgba(0,0,0,0.4);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
  box-sizing: border-box;
">
  <h2 style="margin-top: 0; font-size: 28px; color: #38bdf8;">🧪 Other Ways to Create Arrays & Generate Random Numbers</h2>

  <p style="font-size: 17px; line-height: 1.8; color: #e2e8f0;">
    NumPy offers a variety of functions to create arrays with predefined values or random data. These tools are essential for initializing datasets, testing models, or simulating data.
  </p>

  <ul style="font-size: 16px; color: #cbd5e1; line-height: 1.8; padding-left: 20px;">
    <li><code>np.zeros(shape)</code> – Creates an array filled with zeros.</li>
    <li><code>np.ones(shape)</code> – Creates an array filled with ones.</li>
    <li><code>np.full(shape, value)</code> – Creates an array filled with a specified value.</li>
    <li><code>np.eye(n)</code> – Creates an identity matrix of size <code>n × n</code>.</li>
    <li><code>np.arange(start, stop, step)</code> – Generates values with a fixed step size.</li>
    <li><code>np.linspace(start, stop, num)</code> – Generates evenly spaced values over an interval.</li>
    <li><code>np.random.rand(shape)</code> – Generates random values from a uniform distribution between 0 and 1.</li>
    <li><code>np.random.randn(shape)</code> – Generates random values from a standard normal distribution (mean 0, std 1).</li>
    <li><code>np.random.uniform(low, high, size)</code> – Generates random values from a uniform distribution between <code>low</code> and <code>high</code>.</li>
  </ul>

  <pre style="
    background-color: #0f172a;
    color: #f8fafc;
    padding: 15px;
    border-radius: 10px;
    font-size: 15px;
    overflow-x: auto;
  "><code># 🧠 Difference between random generators:
# np.random.rand → Uniform distribution [0, 1)
# np.random.randn → Normal distribution (mean=0, std=1)
# np.random.uniform → Uniform distribution over custom range [low, high)</code></pre>

  <p style="font-size: 15px; color: #94a3b8;">
    🧠 These functions help you initialize arrays for simulations, testing, and algorithm development with full control over structure and randomness.
  </p>
</div>


In [ ]:
arr0 = np.zeros((2, 3), dtype=np.int64)
arr0

In [ ]:
arr1 = np.ones([3, 3])
arr1

In [ ]:
arr2 = np.full((2, 2), 2)
arr2

In [ ]:
arr3 = np.eye(3)
arr3

In [ ]:
arr4 = np.random.rand(2, 3)
arr4

In [ ]:
arr5 = np.random.randn(3, 3)

In [ ]:
arr5

In [ ]:
arr6 = np.random.uniform(0, 10, (3, 3))
arr6

In [ ]:
arr7 = np.arange(0, 10, 2)
arr7

In [ ]:
arr8 = np.linspace(5, 10, 9)
arr8

<div style="
  width: 100%;
  padding: 40px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 8px 25px rgba(0,0,0,0.4);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
  box-sizing: border-box;
">
  <h2 style="margin-top: 0; font-size: 28px; color: #38bdf8;">🚀 Why Use NumPy?</h2>

  <p style="font-size: 17px; line-height: 1.8; color: #e2e8f0;">
    NumPy is the foundation of numerical computing in Python. It provides a fast, memory-efficient, and expressive way to work with large datasets and mathematical operations.
  </p>

  <ul style="font-size: 16px; color: #cbd5e1; line-height: 1.8; padding-left: 20px;">
    <li>⚡ <strong>Performance:</strong> Vectorized operations are much faster than Python loops.</li>
    <li>📦 <strong>Compact Syntax:</strong> Clean, readable code for complex numerical tasks.</li>
    <li>📐 <strong>Multidimensional Arrays:</strong> Work with matrices, tensors, and high-dimensional data easily.</li>
    <li>🔁 <strong>Broadcasting:</strong> Perform operations between arrays of different shapes without manual looping.</li>
    <li>🧠 <strong>Rich Functionality:</strong> Includes linear algebra, statistics, random sampling, and more.</li>
    <li>🔗 <strong>Integration:</strong> Works seamlessly with libraries like Pandas, Matplotlib, and Scikit-learn.</li>
    <li>🧪 <strong>Essential for Data Science:</strong> Powers most machine learning and scientific computing workflows.</li>
  </ul>

  <p style="font-size: 15px; color: #94a3b8;">
    🧠 Mastering NumPy unlocks the full potential of Python for data analysis, modeling, and AI.
  </p>
</div>


In [ ]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

In [ ]:
%%time
np.dot(arr1_np, arr2_np)

<div style="
  width: 100%;
  padding: 30px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 6px 20px rgba(0,0,0,0.3);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
">
  <h3 style="font-size: 24px; color: #38bdf8;">🧪 Exercise 1: Basic Array Creation</h3>
  <ul style="font-size: 16px; color: #cbd5e1; line-height: 1.8;">
    <li>Create a 5×5 array filled with zeros.</li>
    <li>Generate a 3×4 array filled with ones.</li>
    <li>Create a 2×3 array filled with the value 9.</li>
  </ul>
</div>


In [ ]:
# Answer here

<div style="
  width: 100%;
  padding: 30px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 6px 20px rgba(0,0,0,0.3);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
">
  <h3 style="font-size: 24px; color: #38bdf8;">🧪 Exercise 2: Identity & Shape</h3>
  <ul style="font-size: 16px; color: #cbd5e1; line-height: 1.8;">
    <li>Create an identity matrix of size 6.</li>
    <li>Check the shape of the identity matrix.</li>
    <li>Reshape a 1D array of 12 elements into a 3×4 matrix.</li>
  </ul>
</div>


In [ ]:
# Answer here

<div style="
  width: 100%;
  padding: 30px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 6px 20px rgba(0,0,0,0.3);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
">
  <h3 style="font-size: 24px; color: #38bdf8;">🧪 Exercise 3: Range & Spacing</h3>
  <ul style="font-size: 16px; color: #cbd5e1; line-height: 1.8;">
    <li>Use <code>np.arange</code> to generate values from 0 to 30 with step 3.</li>
    <li>Use <code>np.linspace</code> to generate 8 values between -1 and 1.</li>
    <li>Reshape the <code>arange</code> result into a 2D array.</li>
  </ul>
</div>


In [ ]:
# Answer here

<div style="
  width: 100%;
  padding: 30px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 6px 20px rgba(0,0,0,0.3);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
">
  <h3 style="font-size: 24px; color: #38bdf8;">🧪 Exercise 4: Random Generators</h3>
  <ul style="font-size: 16px; color: #cbd5e1; line-height: 1.8;">
    <li>Generate a 4×4 array using <code>np.random.rand</code>.</li>
    <li>Generate 10 values from a normal distribution using <code>np.random.randn</code>.</li>
    <li>Generate 6 values between 100 and 200 using <code>np.random.uniform</code>.</li>
  </ul>
</div>


In [ ]:
# Answer here

<div style="
  width: 100%;
  padding: 30px;
  border-radius: 20px;
  background: linear-gradient(135deg, #1e293b, #334155);
  box-shadow: 0 6px 20px rgba(0,0,0,0.3);
  font-family: 'Segoe UI', sans-serif;
  color: #f1f5f9;
">
  <h3 style="font-size: 24px; color: #38bdf8;">🧪 Exercise 5: Comparison & Filtering</h3>
  <ul style="font-size: 16px; color: #cbd5e1; line-height: 1.8;">
    <li>Create an array of 10 random integers between 1 and 100.</li>
    <li>Filter out values greater than 50.</li>
    <li>Count how many values are less than 30.</li>
  </ul>
</div>


In [ ]:
# Answer here